version: '3.1'

services:
  mongo:
    container_name: food-swipe-db
    image: mongo:5.0.3
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - food-swipe-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
networks:
  food-swipe-network:
    driver: bridge